任意の曜日をカレンダーの開始日にできるようにする
leader22/cal pull request #9
Opened 2023-02-13 06:34 UTC by studio-kakky

2023-02-13 07:40 UTC, studio-kakky reviewed
@leader22 
任意の曜日をカレンダーの開始日として指定できるように機能追加しました。
`options.fromMonday` の指定も後方互換として指定できるようにしています。

レビューいただけると嬉しいですー。

2023-02-13 07:40 UTC, studio-kakky commented on src/cal.js
> +                                   : defaultMap.slice(firstDayOfWeek).concat(defaultMap.slice(0, firstDayOfWeek))
開始日とし日曜、月曜日以外が渡された場合でも、曜日のラベルを並び替えて渡すようにしました。

2023-02-13 07:40 UTC, studio-kakky commented on src/cal.js
> +        return !!fromMonday ? 1 : 0;
`options.firstDayOfWeek` が渡されたて、適切な場合はその値をカレンダーの始まりの曜日としました。
それ以外は`options.fromMonday` の値をみて0 or 1を返します。

2023-02-13 07:40 UTC, studio-kakky commented on src/cal.js
> +      this.firstDayOfWeek = utils.getFirstDayOfWeek(options.firstDayOfWeek, options.fromMonday);
`options.firstDayOfWeek` と `options.fromMonday` から週の始まりの曜日を決定。ロジックは前述の通り

2023-02-13 07:40 UTC, studio-kakky commented on src/cal.js
> +            return dayGap < 0 ? 6 + dayGap : dayGap - 1;
`_generateCalArr` を見たところ、コメントの通り、

-1: カレンダーは1日から始まる
5: カレンダーは1日の6日前から

となっていたので、月の初日の曜日が `firstDayOfWeek` と一致する時に -1 を返すようにしています。
複雑で間違えそうなのでテスト追加しました。

2023-02-13 07:40 UTC, studio-kakky commented on test/constructor.js
> +})
カレンダーの開始日と終了日のテストを追加しています。

2023-02-13 07:40 UTC, studio-kakky commented on test/constructor.js
> +})
曜日のラベルのテストを追加しています。

2023-02-13 08:02 UTC, leader22 requested changes
PRありがとうございます。

（もはや何も覚えていないので）基本的にはLGTMとしてマージしたいんですが、READMEの用法の部分も変更に沿って反映しておいてほしいです！

2023-02-15 07:38 UTC, studio-kakky reviewed
@leader22 
Readme修正しました。
再度レビューをお願いします。

2023-02-15 07:38 UTC, studio-kakky commented on README.md
> +    // 月曜はじまり or NOT（falseは日曜始まり）firstDayOfWeekが指定されている場合は無視される。
@leader22 
Readmeのusageに変数追加しましたー。

2023-02-16 02:06 UTC, leader22 requested changes
やっと思い出し、意味を理解しました（たぶん）

その上でレビュー2点です。

### 1. README

このPRはつまり、`options.fromMonday`の上位互換な機能である、`options.firstDayOfWeek`を実装したということですよね？

以前は`0`-`1`しか取れなかったのが、`0`-`6`で取れるようになると。

そういう意味では、`fromMonday`はもはや存在価値がないと思うので、`[非推奨]`みたいに書いておきたいです。

```diff
index 9dffac7..b227bac 100644
--- a/README.md
+++ b/README.md
@@ -41,11 +41,15 @@ const cal = new Cal({

     // 週の始まりの曜日 0:日曜 1:月曜 ... 6:土曜
     firstDayOfWeek: 2,
-
-    // 月曜はじまり or NOT（falseは日曜始まり）firstDayOfWeekが指定されている場合は無視される。
+    // [非推奨] 月曜はじまり or NOT（falseは日曜始まり）
+    // firstDayOfWeekが指定されている場合は無視され、以下は等価
+    // firstDayOfWeek: 0 === fromMonday: false
+    // firstDayOfWeek: 1 === fromMonday: true
     fromMonday: true,

     // 未指定の場合は、「月火水木金土日」フォーマット
+    // firstDayOfWeekを指定する場合は、並び替えたものを渡す必要がある
     dayStrArr: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
 });
```

という具合に。

### コード

インラインじゃなくてすいませんなのですが、こんな具合にしたいです。

```diff
diff --git a/src/cal.js b/src/cal.js
index 0139644..56f2c18 100644
--- a/src/cal.js
+++ b/src/cal.js
@@ -43,8 +43,8 @@ export default class Cal {
       this.month = (options.month|0) || today.month;
       this.date  = (options.date|0)  || today.date;

-      this.firstDayOfWeek = utils.getFirstDayOfWeek(options.firstDayOfWeek, options.fromMonday);
-      this._weekMap = utils.getWeekMap(options.dayStrArr, this.firstDayOfWeek);
+      const firstDayOfWeek = utils.getFirstDayOfWeek(options.firstDayOfWeek, options.fromMonday);
+      this._weekMap = utils.getWeekMap(options.dayStrArr, firstDayOfWeek);
       this._calArr  = this._generateCalArr();
       this._dayArr  = this._generateDayArr();
     }
@@ -58,6 +58,8 @@ export default class Cal {
     }

     _generateCalArr() {
+        const { GAP } = this._weekMap;
+
         // monthのoriginは0から
         const thisFirstDateObj = new Date(this.year, this.month - 1, 1);
         // 次月の0day目は、今月の末日
@@ -69,10 +71,8 @@ export default class Cal {

         // この値により、カレンダーの開始日が決まる。
         // -1: 開始日は1日 0: 1日の1日前から（前月最終日）... 5: 1日の6日前からとなる。
-        const thisFirstDayIdx = (() => {
-            const dayGap = thisFirstDateObj.getDay() - this.firstDayOfWeek;
-            return dayGap < 0 ? 6 + dayGap : dayGap - 1;
-        })();
+        const tempDayGap = thisFirstDateObj.getDay() - GAP;
+        const thisFirstDayIdx = tempDayGap < 0 ? 6 + tempDayGap : tempDayGap - 1;

         // 今月が1月なら、先月は12月で去年になる
         const mayLastYear = (thisMonth === 1) ? thisYear - 1 : thisYear;
```

- `this.firstDayOfWeek`で抱え続ける理由はなさそうだったのでやめる
- インラインの即時関数は使わない（スコープ切ってるのに結局outerな変数みちゃってるし）

- - -

理解あってますかね？

2023-02-16 04:55 UTC, studio-kakky commented
@leader22 
> このPRはつまり、options.fromMondayの上位互換な機能である、options.firstDayOfWeekを実装したということですよね

理解あっていますー。
そして、レビューありがとうございます！
対応します。

2023-02-16 05:02 UTC, studio-kakky reviewed
@leader22 
ご指摘いただいた箇所を修正しましたー。
再度レビューいただけると幸いです。

2023-02-16 05:02 UTC, studio-kakky commented on README.md
>      fromMonday: true,
fromMondayを非推奨の値としてREADMEに追記しました。

2023-02-16 05:02 UTC, studio-kakky commented on src/cal.js
> +      this._weekMap = utils.getWeekMap(options.dayStrArr, firstDayOfWeek);
firstDayOfWeekをconstに

2023-02-16 05:02 UTC, studio-kakky commented on src/cal.js
> +        const thisFirstDayIdx = tempDayGap < 0 ? 6 + tempDayGap : tempDayGap - 1
即時関数を止めました

2023-02-16 05:08 UTC, leader22 approved these changes
👍🏻 👍🏻 

minorアップデートとして、このあとnpmにもあげます！

2023-02-16 05:08 UTC, merged

2023-02-16 05:15 UTC, leader22 commented
`v1.2.1`として公開されました〜 🚀